jksdlj
saumya665/algorithm pull request #19
Opened 2017-10-26 02:10 UTC by saumya665

2017-10-26 03:06 UTC, evo777 commented on solutions/findMax.js
> +  if(linkedL==null){
I would add `linkedL.next === head` because what if a linked list is a loop.

2017-10-26 03:06 UTC, evo777 commented on solutions/findMax.js
> +const findMax=(linkedL,max=0)=>{
Add another parameter called: `head=linkedL`

2017-10-28 05:54 UTC, seemcat requested changes
I agree with E-man.

2017-10-30 18:02 UTC, seemcat approved these changes

2017-10-30 18:10 UTC, merged